# Generated by Django 3.2.9 on 2022-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrdctModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prdct_Name', models.CharField(max_length=250)),
                ('Prdct_Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Address', models.CharField(max_length=250)),
                ('User_Gender', models.CharField(max_length=10)),
                ('User_Age', models.IntegerField()),
                ('User_Photo', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
