# Generated by Django 3.2.9 on 2022-07-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_cartmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartmodel',
        ),
    ]
